-- ============================================================
-- AgroSat - Schema do banco (H2)
-- ============================================================
-- Este script reflete o mapeamento JPA das entidades, no dialeto H2,
-- equivalente ao que o Hibernate gera com ddl-auto=create-drop.
--
-- Para exportar do banco em execução: acesse o H2 Console em
-- http://localhost:8080/h2-console (JDBC URL: jdbc:h2:mem:agrosat,
-- user: sa, sem senha) e rode:  SCRIPT TO 'schema_export.sql';
-- ============================================================

DROP TABLE IF EXISTS alertas;
DROP TABLE IF EXISTS dados_satelite;
DROP TABLE IF EXISTS sensores;
DROP TABLE IF EXISTS propriedades;
DROP TABLE IF EXISTS culturas;
DROP TABLE IF EXISTS produtores;

CREATE TABLE produtores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    email       VARCHAR(200) NOT NULL UNIQUE,
    telefone    VARCHAR(20),
    senha_hash  VARCHAR(255) NOT NULL,
    criado_em   TIMESTAMP(6)
);

CREATE TABLE culturas (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE propriedades (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150) NOT NULL,
    localizacao    VARCHAR(300) NOT NULL,
    area_hectares  NUMERIC(10, 2),
    produtor_id    BIGINT NOT NULL,
    cultura_id     BIGINT,
    criado_em      TIMESTAMP(6),
    CONSTRAINT fk_prop_produtor FOREIGN KEY (produtor_id) REFERENCES produtores (id),
    CONSTRAINT fk_prop_cultura  FOREIGN KEY (cultura_id)  REFERENCES culturas (id)
);

CREATE TABLE sensores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(30) NOT NULL,   -- UMIDADE_SOLO | TEMPERATURA | PLUVIOMETRO
    valor           NUMERIC(7, 2) NOT NULL,
    data_hora       TIMESTAMP(6) NOT NULL,
    propriedade_id  BIGINT NOT NULL,
    CONSTRAINT fk_sensor_prop FOREIGN KEY (propriedade_id) REFERENCES propriedades (id)
);

CREATE TABLE dados_satelite (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(10) NOT NULL,   -- NDVI | CLIMA
    ndvi            NUMERIC(5, 3),
    precipitacao_mm NUMERIC(7, 2),
    temp_min        NUMERIC(5, 2),
    temp_max        NUMERIC(5, 2),
    data_coleta     DATE NOT NULL,
    propriedade_id  BIGINT NOT NULL,
    CONSTRAINT fk_satelite_prop FOREIGN KEY (propriedade_id) REFERENCES propriedades (id)
);

CREATE TABLE alertas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(10) NOT NULL,   -- SECA | PRAGA
    severidade      VARCHAR(10) NOT NULL,   -- BAIXA | MEDIA | ALTA
    mensagem        VARCHAR(500) NOT NULL,
    data_criacao    TIMESTAMP(6),
    lida            BOOLEAN NOT NULL,
    propriedade_id  BIGINT NOT NULL,
    CONSTRAINT fk_alerta_prop FOREIGN KEY (propriedade_id) REFERENCES propriedades (id)
);
